### ISSUE TITLE
FR: do device setup in parallel

### ISSUE THREAD

**Issue by adorokhine** [google/mobly#102]
For large testbeds, the time it takes to load snippets and sl4a is quite significant. Would be very nice to be able to easily do this setup in parallel.

I realize this code is part of the user test class, but perhaps we can make a utility method to perform some action for every device in parallel?

**Comment by xpconanfan** [comment]
Something like `android_device.load_snippets(ads, <name>, <package>)`?

**Comment by xpconanfan** [comment]
Or something more generic like `android_device.for_each_parallel(ads, <lambda>)`?

**Comment by xpconanfan** [comment]
Or may even be `controller.for_each_parallel(ads, <lambda>)`...

**Comment by adorokhine** [comment]
Either one... no reason it has to be in android_device or controller; we can make utils.for_each_parallel(objs, func)

**Comment by xpconanfan** [comment]
Actually, can't people just use `utils.concurrent_exec` or Python's `map` directly?

**Comment by xpconanfan** [comment]
This seems like something a user can do with `utils.concurrent_exec(func, ads)` already.
Closing
