### ISSUE TITLE
[monsoon] Clean up code

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#106]
Current monsoon controller code is fairly old.
We need to improve the code with best practices of today and remove unused APIs like `execute_sequence_and_measure`.

**Comment by dpursehouse** [comment]
while you're in the monsoon module, it might be worth fixing these problems highlighted by pyflakes:

```
mobly/controllers/monsoon.py:300: list comprehension redefines 'x' from line 298
mobly/controllers/monsoon.py:476: local variable 'voltage_str' is assigned to but never used
mobly/controllers/monsoon.py:477: undefined name 'voltage'
mobly/controllers/monsoon.py:641: undefined name 'mon'
mobly/controllers/monsoon.py:709: local variable 'history_deque' is assigned to but never used
mobly/controllers/monsoon.py:745: local variable 'e' is assigned to but never used
```

**Comment by xpconanfan** [comment]
Also need to clean up sleeps

**Comment by winterfroststrom** [comment]
Need to also make it testable as we have basically no unit test coverage for it right now

**Comment by xpconanfan** [comment]
The Monsoon controller code is now removed in favor of Monsoon's official solution
