### ISSUE TITLE
Docstring errors found by sphinx api doc generation tool

### ISSUE THREAD

**Issue by yusufm** [google/mobly#119]
/mobly/asserts.py:docstring of mobly.asserts.abort_all:7: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.abort_all_if:8: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.abort_class:10: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.abort_class_if:11: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.assert_equal:10: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.assert_false:7: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.assert_true:7: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.explicit_pass:10: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.fail:6: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.skip:6: ERROR: Unexpected indentation.
/mobly/asserts.py:docstring of mobly.asserts.skip_if:7: ERROR: Unexpected indentation.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass:12: ERROR: Unexpected indentation.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass:13: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass:15: ERROR: Unexpected indentation.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass:16: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass.run:7: ERROR: Unexpected indentation.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass.run:8: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass.run_generated_testcases:15: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass.run_generated_testcases:17: ERROR: Unexpected indentation.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass.run_generated_testcases:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass.unpack_userparams:20: ERROR: Unexpected indentation.
/mobly/base_test.py:docstring of mobly.base_test.BaseTestClass.unpack_userparams:17: WARNING: Inline strong start-string without end-string.
/mobly/config_parser.py:docstring of mobly.config_parser.load_test_config_file:10: ERROR: Unexpected indentation.
/mobly/logger.py:docstring of mobly.logger.epoch_to_log_line_timestamp:7: ERROR: Unexpected indentation.
/mobly/logger.py:docstring of mobly.logger.setup_test_logger:7: ERROR: Unexpected indentation.
/mobly/records.py:docstring of mobly.records.TestResult:8: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/records.py:docstring of mobly.records.TestResult.json_str:9: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/records.py:docstring of mobly.records.TestResult.json_str:11: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/records.py:docstring of mobly.records.TestResultRecord.json_str:9: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/signals.py:docstring of mobly.signals.TestSignal:7: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner:11: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner:13: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner:14: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner:16: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner:17: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner:21: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner:23: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner.register_controller:10: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner.register_controller:13: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner.register_controller:22: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner.register_controller:31: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner.register_controller:33: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner.register_controller:46: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.TestRunner.register_controller:48: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.execute_one_test_class:9: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/test_runner.py:docstring of mobly.test_runner.execute_one_test_class:11: ERROR: Unexpected indentation.
/mobly/test_runner.py:docstring of mobly.test_runner.main:11: ERROR: Unexpected indentation.
/mobly/utils.py:docstring of mobly.utils.concurrent_exec:10: ERROR: Unexpected indentation.
/mobly/utils.py:docstring of mobly.utils.find_field:9: ERROR: Unexpected indentation.
/mobly/utils.py:docstring of mobly.utils.find_files:7: ERROR: Unexpected indentation.
/mobly/utils.py:docstring of mobly.utils.start_standing_subprocess:14: ERROR: Unexpected indentation.
/mobly/controllers/android_device.py:docstring of mobly.controllers.android_device.AndroidDevice:10: ERROR: Unexpected indentation.
/mobly/controllers/android_device.py:docstring of mobly.controllers.android_device.AndroidDevice:11: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/android_device.py:docstring of mobly.controllers.android_device.AndroidDevice:17: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/controllers/android_device.py:docstring of mobly.controllers.android_device.AndroidDevice:19: ERROR: Unexpected indentation.
/mobly/controllers/android_device.py:docstring of mobly.controllers.android_device.AndroidDevice.cat_adb_log:7: ERROR: Unexpected indentation.
/mobly/controllers/android_device.py:docstring of mobly.controllers.android_device.AndroidDevice.run_iperf_client:9: ERROR: Unexpected indentation.
/mobly/controllers/android_device.py:docstring of mobly.controllers.android_device.AndroidDeviceLoggerAdapter:6: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/controllers/android_device.py:docstring of mobly.controllers.android_device.filter_devices:7: ERROR: Unexpected indentation.
/mobly/controllers/attenuator.py:docstring of mobly.controllers.attenuator:5: ERROR: Unexpected indentation.
/mobly/controllers/attenuator.py:docstring of mobly.controllers.attenuator:10: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/controllers/attenuator.py:docstring of mobly.controllers.attenuator:12: ERROR: Unexpected indentation.
/mobly/controllers/attenuator.py:docstring of mobly.controllers.attenuator:16: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/attenuator.py:docstring of mobly.controllers.attenuator:17: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/attenuator.py:docstring of mobly.controllers.attenuator.AttenuatorPath:10: ERROR: Unexpected indentation.
/mobly/controllers/attenuator.py:docstring of mobly.controllers.attenuator.AttenuatorPath:12: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.Monsoon.execute_sequence_and_measure:18: ERROR: Unexpected indentation.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.Monsoon.execute_sequence_and_measure:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.Monsoon.execute_sequence_and_measure:28: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.Monsoon.execute_sequence_and_measure:28: WARNING: Inline emphasis start-string without end-string.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.Monsoon.execute_sequence_and_measure:28: WARNING: Inline strong start-string without end-string.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.Monsoon.set_voltage:6: ERROR: Unexpected indentation.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.Monsoon.take_samples:10: ERROR: Unexpected indentation.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.Monsoon.take_samples:11: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.MonsoonProxy:9: ERROR: Unexpected indentation.
/mobly/controllers/monsoon.py:docstring of mobly.controllers.monsoon.MonsoonProxy:10: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/sniffer.py:docstring of mobly.controllers.sniffer.Sniffer.start_capture:12: ERROR: Unexpected indentation.
/mobly/controllers/sniffer.py:docstring of mobly.controllers.sniffer.Sniffer.start_capture:44: ERROR: Unexpected indentation.
/mobly/controllers/sniffer.py:docstring of mobly.controllers.sniffer.create:7: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/controllers/sniffer.py:docstring of mobly.controllers.sniffer.create:10: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.get_event_q:8: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.handle_event:10: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.handle_event:12: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.handle_event:13: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.handle_event:15: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.handle_event:16: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.pop_event:10: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.pop_events:22: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.wait_for_event:11: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.wait_for_event:12: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.wait_for_event:12: WARNING: Inline emphasis start-string without end-string.
/mobly/controllers/android_device_lib/event_dispatcher.py:docstring of mobly.controllers.android_device_lib.event_dispatcher.EventDispatcher.wait_for_event:12: WARNING: Inline strong start-string without end-string.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base:7: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base:10: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base:14: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base:16: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base:20: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base.JsonRpcClientBase:13: ERROR: Unexpected indentation.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base.JsonRpcClientBase:14: WARNING: Block quote ends without a blank line; unexpected unindent.
/mobly/controllers/android_device_lib/jsonrpc_client_base.py:docstring of mobly.controllers.android_device_lib.jsonrpc_client_base.JsonRpcClientBase.connect:11: WARNING: Definition list ends without a blank line; unexpected unindent.
/mobly/docs/mobly.controllers.attenuator_lib.rst:10: WARNING: autodoc: failed to import module u'mobly.controllers.attenuator_lib.minicircuits'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.5.2-py2.7.egg/sphinx/ext/autodoc.py", line 551, in import_object
      __import__(self.modname)
        File "/mobly/controllers/attenuator_lib/minicircuits.py", line 25, in <module>
	    from mobly.controllers.attenuator_lib import telnet_client
	    ImportError: cannot import name telnet_client

**Comment by xpconanfan** [comment]
Fixed by #339
