### ISSUE TITLE
Need to resolve versioning of mobly api documentation generation through readthedocs.org

### ISSUE THREAD

**Issue by yusufm** [google/mobly#128]
Currently we have a pip requirements file (docs/rtd_requirements.txt) that is used by the readthedocs.org to generate mobly api documentation.

This causes the code thats used to generate the documentation to come from the latest version of mobly thats available through pip, and not from the latest code in master branch.

We need to fix the documentation setup so that readthedocs build grabs the right version of code from the branch.

**Comment by xpconanfan** [comment]
I think getting it from the latest pip release is good.
I prefer to have the docs generated from actual releases, instead of always pointing to head.

So we just need to make the docs show the current version number. :)

**Comment by yusufm** [comment]
If thats the case, we can pickup the version number from that. See how flask does it in their file:

https://github.com/pallets/flask/blob/master/docs/conf.py#L70

**Comment by xpconanfan** [comment]
Looks good.
Not sure why they are doing the split and join though...

**Comment by yusufm** [comment]
Looks like they only want the major.minor only, not others.

**Comment by xpconanfan** [comment]
we can choose to use all three x.x.x right?

**Comment by xpconanfan** [comment]
Fixed by #339
