### ISSUE TITLE
controllers/android_device.py throws an exception on android configuration with just string

### ISSUE THREAD

**Issue by k2fong** [google/mobly#144]
Seems like an earlier checkin to switch to using base64 string to load configuration might have introduced a bug in mobly/controllers/android_device.create(configs).  I was hitting an issue where I specified the android device serial in string format in my configuration file but was failing the isinstance check with str, so instead it tries to interpret my android config as a dict format and fails.  Changing the isinstance check with basestring instead of str seems to have solved the problem.

Here is the snippet of the exception thrown.
mobly/controllers/android_device.py", line 81, in create
mobly/controllers/android_device.py", line 219, in get_instances_with_configs
MoblyTest [ln]     serial = c.pop('serial')
MoblyTest [ln] AttributeError: 'str' object has no attribute 'pop'

**Comment by xpconanfan** [comment]
Hi k2fong,

It appears that you're running an older version of Mobly.
Can you try ToT and see if it fixes this problem?
Also, which version of Python are you using? We considered using `basestring` but it does not exist in Python3, so we opted with the current solution.

Thanks,
Ang
