### ISSUE TITLE
Make Mobly run on Windows

### ISSUE THREAD

**Issue by adorokhine** [google/mobly#151]
Mobly is currently unix-only. It would be nice to have Windows support.

**Comment by xpconanfan** [comment]
What else do we need to do before closing this?

**Comment by adorokhine** [comment]
We'd need to get the unit tests at least passing on Windows. (There's another bug for getting them run continuously, which would probably be a larger effort).

**Comment by xpconanfan** [comment]
K. Is there a bug tracking the failing unit tests?

**Comment by adorokhine** [comment]
I was treating the unit tests on Windows as being under the umbrella of this bug. :)

**Comment by xpconanfan** [comment]
Closing this one as the feature support is done.
Let's keep tracking unit test for win in #154.
