### ISSUE TITLE
Snippets are not compatible with UIAutomator

### ISSUE THREAD

**Issue by adorokhine** [google/mobly#166]
'am instrument' only sets up a UiAutomationConnection in -w mode (I don't know why). Snippets are not run in wait mode, so UiAutomationConnection is null. This crashes uiautomator, which needs that proxy object for privileged operations back to the shell.

We need to start the snippets in -w mode, using something like `start_standing_subprocess`.

**Comment by xpconanfan** [comment]
Do we need to start all snippet this way?
I'd prefer not having to hold these processes unless necessary.

**Comment by adorokhine** [comment]
> I'd prefer not having to hold these processes unless necessary.

Why's that?

**Comment by xpconanfan** [comment]
less management, less complexity, less code, less work :P

So do we need to start all snippet this way?

**Comment by adorokhine** [comment]
> less management

I think the only new management we have to do is calling stop_standing_subprocess() right?

> less complexity

Actually if we have codepaths for both, there's more complexity because we have to implement and test both ways of starting snippets.

Also (most importantly for me) the complexity will be exposed to the user, because now they'll have to know to load their snippet differently than before if/when it gets UIAutomator calls.

And there's no good way for us to produce a good error to help them here since the symptom will be that UIAutomator.getDevice() will just return `null` on the Java side. That's not something we can catch/wrap.

> less code, less work

More code and work to support both, see above

**Comment by xpconanfan** [comment]
Can we ask the adb team about '-w' and understand why it's required for ui automator first?

**Comment by adorokhine** [comment]
Sure, can do. But I'm not sure what you mean by asking them 'first' -- adb versions are slow to roll out and have slow adoption. We still have to support adb 1.0.32 in Mobly. So even if they remove this requirement in a new version, I don't think it would matter much to us from a support perspective, would it?

**Comment by xpconanfan** [comment]
I'm not saying it's a bug in adb. Just looking to understand more about the rationale behind it. May give us some insights on how to resolve it.

**Comment by adorokhine** [comment]
> Just looking to understand more about the rationale behind it.

Looks like UIAutomator works by keeping a shell connection open and sending privileged operations there by IPC for execution in shell context. So doesn't seem like a requirement we can drop for UIAutomator.
