### ISSUE TITLE
Support heterongenous AndroidDevice specs

### ISSUE THREAD

**Issue by dthkao** [google/mobly#176]
Right now in the config 
{"AndroidDevice":["abc","def"]}
 and 
{"AndroidDevice":[{"serial":"abc"},{"serial":"def"}]}
are supported but not
{"AndroidDevice":["abc",{"serial":"def"}]}.

Can we support the mixed formats?

**Comment by xpconanfan** [comment]
Discussed offline.
Decided not to do this.
