### ISSUE TITLE
logcat is empty for some NBU devices

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#190]
When starting adb logcat, we use `-b all` to catch all buffers.

But some NBU devices (like HTC Desire 526g+) don't have the buffer option "all", and their adb logcat would only have one line saying "Unable to open log device '/dev/log/all': No such file or directory".

We need to handle this properly so we get the logs from the buffers the device does have, like 'main', 'system', 'radio', and 'events'.

**Comment by dthkao** [comment]
Can you override with "adb_logcat_param" in the config?
