### ISSUE TITLE
Make `AndroidDevice.take_bug_report` more useful

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#193]
Right now, `AndroidDevice.take_bug_report` is meant to be used in functions like `BaseTestClass.on_fail`, because it requires a test name and a test begin time.

There's no reason to lock the usage of `AndroidDevice.take_bug_report` like this. We should generalize the usage to make it work in more situations.

**Comment by winterfroststrom** [comment]
Oh, I just realized that http://go/gh/google/mobly/pull/576 implements half of this, so the only thing that's left is giving a default test name like "bugreport" maybe
