### ISSUE TITLE
Consistent behavior from errors in setup and teardown

### ISSUE THREAD

**Issue by dthkao** [google/mobly#264]
Currently we have the following

Exception in `setup_class`: Extra result entry, mark test cases as skipped
Exception in `setup_test`: Mark test as error using details
Exception in `teardown_test`: Mark test as error using extra_errors
Exception in `teardown_class`: No record

I propose the following for the sake of consistency (both with pyunit and with self):

Exception in `setup_class`:
    No extra result entry, mark test cases as skipped, add to extra_errors for each result
Exception in `setup_test`: Either
    1)  mark test case result as skipped and use extra_errors for error message
    2)  mark test case as error and use details
Exception in `teardown_test`: Either (while being consistent with `setup_test`)
    3)  Do not change the test case result (leave it as is) and use `extra_errors` for error message
    4)  mark test case as error and use `details`
Exception in `teardown_class`:
    Do not change the test case results, add to `extra_errors` for all non-skipped results

**Comment by xpconanfan** [comment]
1. There is an additional entry for setup_class in this case and it is marked error. Maybe the entries for test cases shouldn't have error msg at all as they are just repeating the same thing from setup_test's entry, which can be a lot of repetition with no added value and make the summary hard to read.
2. no change needed?
3. This is for consistency with pyunit and other internal test frameworks.
4. This is a bug. teardown_class's reporting behavior should also be consistent with that of pyunit's `tearDownClass`.

**Comment by dthkao** [comment]
1. This leads to an inconsistent number of records.

2. & 3. This behavior should be coupled and self consistent. If current behavior for teardown_test is considered "consistent" with pyunit, then option 1 would be consistent with pyunit. Additionally, the assertiong that current behavior for 3 is consistent with pyunit is not quite correct: in pyunit it's possible to pass a test but have an error in teardown, with the test still recorded as pass.

**Comment by dthkao** [comment]
Also re: point 1, the following test has multiple tests but a setUpClass error results in

$ python pytesttest.py 
E
======================================================================
ERROR: setUpClass (__main__.TestErrorReporting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pytesttest.py", line 7, in setUpClass
    raise Exception('ouch class')
Exception: ouch class

----------------------------------------------------------------------
Ran 0 tests in 0.002s

FAILED (errors=1)

**Comment by xpconanfan** [comment]
Discussed offline.
Things that need fixing:
* Errors thrown in `teardown_test` should be recorded the same as errors thrown in test body and into the details of the record. stacktraces should be collected too.
* `teardown_class` should be accounted the same as `setup_class`, but it does not affect the results of executed tests.

**Comment by dthkao** [comment]
> Errors thrown in teardown_test should be recorded the same as errors thrown in test body and into the details of the record. stacktraces should be collected too.

Actually I think we agreed that errors in teardown_test should be recorded the same as errors in the test body only if the test body passed. Otherwise errors in teardown_test should be "extra".

**Comment by xpconanfan** [comment]
Yes, that's what I meant...

**Comment by xpconanfan** [comment]
All things mentioned have been fixed! Yay!
