### ISSUE TITLE
Make the log level to stdout customizable

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#278]
Right now Mobly writes to stdout in INFO level by default.
We can provide a MoblyParam to change this.

**Comment by dthkao** [comment]
Would a flag be more appropriate?

**Comment by xpconanfan** [comment]
Flag meaning?
This is just to be consistent with how LogPath is set.

**Comment by dthkao** [comment]
I had meant a command line flag, but I guess consistency is good too. :)

Doe this only affect stdout, or also the log files as well?

**Comment by xpconanfan** [comment]
Only affects stdout as the title says... Not sure how useful this is though

**Comment by xpconanfan** [comment]
This is done
