### ISSUE TITLE
Support custom logger prefix in AndroidDevice controller

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#28]
Right now the logger prefix for Android device controller can not be changed.
Sometimes it is useful to be able to change the prefix to be more fitting for the context of the test.
E.g. Instead of `[AndroidDevice|<serial>]`, `[AndroidDevice|caller]` could be more useful in a call test.

**Comment by dthkao** [comment]
Are you just thinking of addressing this using the testbed config? or with a method call after Android device controller initialization?

**Comment by xpconanfan** [comment]
In AndroidDevice, not config, so it's explicit?
