### ISSUE TITLE
Log the contents of config file at the debug level early

### ISSUE THREAD

**Issue by dthkao** [google/mobly#295]
This helps in debugging remote user's malformed json/yaml or configs that don't adhere to schema.

**Comment by xpconanfan** [comment]
where do we want this to go, summary yaml or regular log?

**Comment by dthkao** [comment]
I vote DEBUG log. Preferably as the read in string (to expose any poor json/yaml formatting).

**Comment by xpconanfan** [comment]
And I assume the config here is the user config file content as is?

**Comment by dthkao** [comment]
Yessir.

**Comment by xpconanfan** [comment]
Hmm, so what kind of error do we want to catch with this?
If the config format is incorrect, the logger won't even get set up so we won't even get a log file...
