### ISSUE TITLE
[Py2] Unicode is not properly handled in string conversions

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#358]
In Py2, we sometimes get:
```
...
mobly/records.py", line 102, in _test_end
I 16:41:23:508 UTC     self.details = str(e)
I 16:41:23:508 UTC UnicodeEncodeError: 'ascii' codec can't encode character u'\u2022' in position 32280: ordinal not in range(128)
```
This is caused by `str` not able to handle unicode properly in py2.

**Comment by xpconanfan** [comment]
This seems to solve the problem for all cases:
```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by dthkao** [comment]
That's a generally frowned upon approach.

**Comment by xpconanfan** [comment]
What's a better way? Care to share some examples? :)

**Comment by dthkao** [comment]
https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by xpconanfan** [comment]
That explains why not to use it, which I understand.
What alternatives do you suggest? Because I don't see an easy way to solve this for all places.

**Comment by xpconanfan** [comment]
A better question: how should we handle unicode for py2?
Do we want to convert them into ascii which makes them lose meaning?
Or do we want to try to keep them as unicode text in our outputs?

**Comment by dthkao** [comment]
Why not use sys.getdefaultencoding? I don't think we should be focing either way.

**Comment by xpconanfan** [comment]
"sys.getdefaultencoding() is always 'ascii' on all systems in Python 2"
I'm not sure how that API solves our problem here. Can you be more explicit?
That does not seem to answer the question "how should we handle unicode for py2"

**Comment by dthkao** [comment]
If the user sets a systemwide default encoding in py2 to something other than ascii we should be using that, and that would be determined by getdefaultencoding. If they don't touch it and it is ascii then convert to ascii. The only thing I am asserting is that Mobly should not be dictating (and changing) system wide encoding.

**Comment by xpconanfan** [comment]
Does that mean the test that reproduces this issue has the default encoding changed?
Can you confirm that?

**Comment by dthkao** [comment]
The test did not change it. It's just that the str() op is assuming ascii and trying to deal with a unicode character that came from the snippet?

**Comment by xpconanfan** [comment]
If the unicode is coming from the Java side, how does calling `sys.getdefaultencoding()` on the host help us here? It'll only say the current system is 'ascii', then what do we do?

**Comment by dthkao** [comment]
It (sys.getdefaultencoding()) will tell us that str() expects ascii and we can either check and strip unicode beforehand, or you could wrap the str() in a try.
