### ISSUE TITLE
Merge existing AndroidDevice RPC service shells into one

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#38]
If possible, would be nice to have an ad shell taking care of all the RPC service launches.
$ mobly_android_shell -s <serial> --service_names sl4a snippet_a

**Comment by adorokhine** [comment]
That's quite a bit more verbose (and more things you have to remember) versus the current invocation:

    $ sl4a_client [-s serial]
    $ snippet_client [-s serial] com.my.package

versus

    $ mobly_android_shell [-s serial] sl4a com.my.package

Any thoughts?

**Comment by xpconanfan** [comment]
well, it'll be one shell where people can use both RPC services, which could be handy?

**Comment by xpconanfan** [comment]
Don't really need this any more. Closing
