### ISSUE TITLE
Majority pass tests

### ISSUE THREAD

**Issue by winterfroststrom** [google/mobly#394]
Add ability to run a test multiple times and mark it as passed even if there are x failures/errors so long as there are x + 1 passes

This is to make inherently unreliable test cases reliable

**Comment by xpconanfan** [comment]
We actually considered this feature before and decided against it.
Maybe the circumstances have changed. Let's discuss offline.

**Comment by xpconanfan** [comment]
We now have proper retries/repeats which mitigates the problem.
Downstream systems can choose to decide how to interpret the final status of the test based on the data.

Closing this for now as the current approach seems sufficient.
