### ISSUE TITLE
Add ro.build.version.sdk to build_info

### ISSUE THREAD

**Issue by winterfroststrom** [google/mobly#402]
Currently, build info only contains ro.build.id and ro.build.type

For some devices, this is probably sufficient because ro.build.id is populated with a lot of information.
However, for other devices, it doesn't contain much information at all.
Additionally, attempting to parse this value is not safe because of it's variability.

Because the sdk version is a pretty important value for debugging, this should be in build_info as well.

**Comment by xpconanfan** [comment]
You can already add any info you want with [this API](http://mobly.readthedocs.io/en/stable/mobly.controllers.html#mobly.controllers.android_device.AndroidDevice.add_device_info)

SDK version can be derived from build number, which is already included.

**Comment by winterfroststrom** [comment]
What do you mean by build number?

**Comment by xpconanfan** [comment]
Build ID

**Comment by winterfroststrom** [comment]
This is NOT in build id.
That's why I wanted to add this.
Read the issue description.

**Comment by xpconanfan** [comment]
Read my comment:
"""
You can already add any info you want with this API
SDK version can be derived from build id, which is already included.
"""

So this is not necessary.

**Comment by xpconanfan** [comment]
This API being
http://mobly.readthedocs.io/en/stable/mobly.controllers.html#mobly.controllers.android_device.AndroidDevice.add_device_info

**Comment by winterfroststrom** [comment]
Considering build_info may be deprecated, handling this on a per user basis is probably better than a general change.
