### ISSUE TITLE
Calling `asserts.abort_all` in `on_fail` crashes Mobly

### ISSUE THREAD

**Issue by winterfroststrom** [google/mobly#406]
When a mobly test raises a TestAbortAll signal from on_fail and setup_test fails, results does not get set on the TestAbortAll signal. This causes an AttributeError instead of the expected TestAbortAll signal, because TestRunner assumes that results is set on all TestAbortAll signals.

**Comment by winterfroststrom** [comment]
Actually, that line should just be deleted

**Comment by xpconanfan** [comment]
I'm not sure what you are trying to do.
Can you describe the use case

**Comment by winterfroststrom** [comment]
I did not triage this quite correctly, basically if you throw a TestAbortAll before you even execute the test, then results doesn't get set.

**Comment by xpconanfan** [comment]
Can you edit the bug with proper information like description of the problem and steps to reprod

**Comment by winterfroststrom** [comment]
editted
