### ISSUE TITLE
Exceptions thrown from `setup_test` lose stacktrace in test logs.

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#409]
The full stack trace logged looks like:

```
Traceback (most recent call last):
  File "mobly/base_test.py", line 363, in exec_one_test
    raise new_e
```

**Comment by matty3** [comment]
Can you provide a sample test where this occurs? I've tried raising an exception in 'setup_test' and the test_log.INFO seems to capture the stack trace.

**Comment by xpconanfan** [comment]
It only occurs if a `signals.TestSignal` is raised.
So you have to reprod with something like `asserts.fail`

**Comment by xpconanfan** [comment]
And the problem is py2 only...
