### ISSUE TITLE
Monsoon module cannot be imported in Windows

### ISSUE THREAD

**Issue by winterfroststrom** [google/mobly#424]
This is because of the import of 'fcntl', which does not exist on Windows.
E   ImportError: No module named fcntl

**Comment by xpconanfan** [comment]
Does this mean the monsoon module won't work on Windows at all?

**Comment by winterfroststrom** [comment]
idk, not familiar with monsoon

**Comment by winterfroststrom** [comment]
but this issue does mean you can't import the monsoon module

**Comment by jeffherman** [comment]
Probably the easiest way to do this is to only import `fcntl` if you're on a Posix system or not running Windows so either:

```
import os
if os.name == 'posix':
    import fcntl
```
or:
```
import platform
if platform.system() != 'Windows':
    import fcntl
```
Subsequently, you would need to deal with the actual `fcntl.lockf` [usage](https://github.com/google/mobly/blob/master/mobly/controllers/monsoon.py#L153) in the code. Some sites recommend [`msvcrt.locking`](https://docs.python.org/2/library/msvcrt.html#msvcrt.locking) while [other sites](https://stackoverflow.com/questions/575328/fcntl-lockf-which-is-better-to-use-for-file-locking) suggest that 

> In Windows on the other hand, you can actively exclusively open a file, and that will block other processes from opening it completely.

 I don't have a Windows machine on hand to test this out.

**Comment by winterfroststrom** [comment]
So, I do have a windows machine to test this on, but I don't have a monsoon or familiarity with them.

We can use kokoro for unit tests on Windows if necessary, but then we don't actually have unit tests for this module either (and to add them, I think you'd have to refactor this module), which is the more fundamental reason why I'm not working on this right now.

**Comment by xpconanfan** [comment]
Closing as we are deprecating the current monsoon code in favor of a new version
