### ISSUE TITLE
Logo Proposal for Mobly

### ISSUE THREAD

**Issue by area55git** [google/mobly#440]
Hello, I wish to cooperate with mobly, for this reason I have decided to design a logo for it. If you like this proposal, I can send you the files.

You can suggest the changes you think are necessary.

[![LOGO_PROPOSAL_FOR_MOBLY.jpg](https://s9.postimg.cc/cfd1j5kkf/LOGO_PROPOSAL_FOR_MOBLY.jpg)](https://postimg.cc/image/8izpn5zkr/)

**Comment by xpconanfan** [comment]
Thanks for the proposal!
We don't think this logo is a good fit for our project.
We are working on a logo internally. So stay tuned :)
