### ISSUE TITLE
Support asynchronous adb commands

### ISSUE THREAD

**Issue by winterfroststrom** [google/mobly#454]
Some adb commands such as instrument/logcat/shell processes are long running and need to be run asynchronously, which means that AdbProxy cannot be used

This falls back to raw adb command strings with utils.start_standing_process, which a non-ideal workflow

So, AdbProxy should support this with some API that returns a future or something

**Comment by xpconanfan** [comment]
One can make custom logic for determining the pass/fail criterial using `test_runner` APIs in a suite already. No need for this.
