### ISSUE TITLE
Set 'utf-8' encoding on all instances of file operations for Windows/Python3 environments

### ISSUE THREAD

**Issue by winterfroststrom** [google/mobly#459]
The current state of things can cause encoding errors

**Comment by winterfroststrom** [comment]
Apparently, this is set by default in python 3.6
https://docs.python.org/3/whatsnew/3.6.html#pep-529-change-windows-filesystem-encoding-to-utf-8
https://docs.python.org/3/whatsnew/3.6.html#pep-529-change-windows-filesystem-encoding-to-utf-8

Additionally, encoding is not a valid keyword for python 2

**Comment by winterfroststrom** [comment]
Testing on windows with python3.6, seems to fail the unit test also

**Comment by winterfroststrom** [comment]
builtins.open (from python future) and io.open (from standard lib) are both okay workarounds, but should be consistent

Prefer io.open?

**Comment by winterfroststrom** [comment]
This changes it:
https://github.com/winterfroststrom/mobly/tree/use_compat_open
which passes unit tests with python 2/3 on Linux/Windows
and passes python 2/3 sample run on Linux

But from the changes in android_device_test indicate that io.open (or builtins.open) only accept unicode arguments, which introduces potential python2 encoding issues

So, seems somewhat dangereous

**Comment by xpconanfan** [comment]
So let's use `io.open`?
