### ISSUE TITLE
`AdbError` should have a serial number attr

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#488]
Our `AdbError` does not include an easily accessible serial number.

When handling an `AdbError`, it is sometimes useful to know which device the command was issued to, especially when you cannot change the code around the adb call directly and have to handle at an upper level.

Is this something worth adding?

**Comment by dthkao** [comment]
aren't some adb commands not device specific?

**Comment by xpconanfan** [comment]
Yes, for those the serial field can simply be `''`?

**Comment by xpconanfan** [comment]
Need to change the timeout error too
