### ISSUE TITLE
Module index not generated on mobly.readthedocs.io

### ISSUE THREAD

**Issue by jeffherman** [google/mobly#553]
The [readthedocs.io `mobly` module page](https://mobly.readthedocs.io/en/latest/py-modindex.html) never gets generated. The [build logs](https://readthedocs.org/api/v2/build/8396866.txt) show:

```
/home/docs/checkouts/readthedocs.org/user_builds/mobly/checkouts/latest/docs/index.rst:30: WARNING: toctree contains reference to nonexisting document 'mobly'
looking for now-outdated files... none found
```

I am unable to repro this locally. This might be a simple fix to [`conf.py`](https://github.com/google/mobly/blob/master/docs/conf.py#L21) by changing line 21 to:

```
sys.path.insert(0, os.path.abspath('../'))
````

**Comment by xpconanfan** [comment]
autodoc gen steps are actually in 
https://github.com/google/mobly/blob/master/docs/README.sphinx

Just need to follow that.
