### ISSUE TITLE
wait_for_standing_subprocess does not work with Python 2

### ISSUE THREAD

**Issue by winterfroststrom** [google/mobly#559]
subprocess.wait() does not take any arguments in Python 2

**Comment by winterfroststrom** [comment]
Replace with psutil.Process.wait(timeout), which raises psutil.TimeoutExpired

one issue is that people are using subprocess32 with python2 for this and explicitly catching the subprocess.TimeoutExpired exception

That exception does not share hierarchy with psutil.TimeoutExpired, which means it's going to break people

**Comment by xpconanfan** [comment]
Closing this as Py2 support will be deprecated.
