### ISSUE TITLE
Bluetooth profile testing

### ISSUE THREAD

**Issue by aglogger** [google/mobly#586]
Am I able to perform automated testing of different Bluetooth profiles with this framework. For example A2DP, HSP, HFP or SPP testing? As far as I can see Mobly Bundled Snippets only includes some functions to connect to A2DP devices.

**Comment by xpconanfan** [comment]
The framework itself does not limit what profile you can use.
The a2dp code in MBS is meant to be an example on what profile tests look
like, not solving all the problems.

You can implement the profiles you need using the snippet library and
create tests for other profiles.

**Comment by aglogger** [comment]
I implemented the BluetoothHeadset profile just like the a2dp example using the snippet library. It's working so far, but I was wondering how I can determine now, if HSP or HFP is used, because Android uses the BluetoothHeadset class for both of them.

**Comment by xpconanfan** [comment]
I think there are actual classes for these profiles. You can refer to the
Android public API doc to see what's available.
