### ISSUE TITLE
Control headphone device

### ISSUE THREAD

**Issue by aglogger** [google/mobly#589]
Is it possible to control a bluetooth headphone device with mobly in any way? For example, simulating pressing the pairing button to run automated tests without having to perform manual operations on the device.

**Comment by xpconanfan** [comment]
Yes.

You can use electric relays to simulate button presses.

**Comment by aglogger** [comment]
Do you might have anything on how to get me started on this, because I haven't had any experience with it yet.

**Comment by xpconanfan** [comment]
@mderu Can you share some links?

**Comment by aglogger** [comment]
What I found out so far is that I have to reverse-engineer the headphone (analyze what happens when pressing a button), then solder a relay to the corresponding positions on the headphone to bridge the circuits and finally control the corresponding relay signals via a PC using python.
Is this basic structure correct so far?
I would still be very happy about some links that explain the process of implementing such a setup.
Thank you ;)

**Comment by mderu** [comment]
Hey @aglogger,

There's a controller found in Android's ACTS that has this functionality already.(https://android.googlesource.com/platform/tools/test/connectivity/+/refs/heads/master/acts/framework/acts/controllers/relay_lib/, https://android.googlesource.com/platform/tools/test/connectivity/+/refs/heads/master/acts/framework/acts/controllers/relay_device_controller.py) We're looking into bringing it into Mobly's controllers, but it's going to take some time to get around to. Feel free use this in the meantime. From the relay devices supported in the library, we've seen the best performance from https://www.sainsmart.com/products/8-channel-12v-usb-relay-module (sain_smart_8_channel_usb_relay_board.py in the above library), although after two years of constant use, some of these have spent their 50,000 switch lifespans.

**Comment by aglogger** [comment]
@mderu Thanks a lot for the tips!
Was I right regarding the basic construction of the setup and could you recommend a headphone or speaker that can be reverse engineered as simply as possible for this purpose?

Concerning the ACTS controller: Can it be used out of the box or do I have to make adjustments?

**Comment by mderu** [comment]
Yes, we pull apart the devices and solder leads onto the button contacts, and attach them to a relay board.

I don't remember the easiest speaker to reverse engineer; most of the headsets take about the same amount of effort. Usually, the more exposed the buttons are, the easier it is to rewire them. Take a look at the headphone classes we have in the relay_lib directory, most of them should specify the exact model they use within the class docstring.

The ACTS controller should be usable out-of-the-box, but you'll need to change the ACTS_CONTROLLER_CONFIG_NAME to MOBLY_CONTROLLER_CONFIG_NAME instead to get it to work with Mobly's register_controller(). If you plan on copying the code and not installing ACTS directly, you may have to install the libftdi/libusb libraries.  The file acts/framework/acts/controllers/relay_lib/sain_smart_8_channel_usb_relay_board.py should have documentation you need on the setup here.
