### ISSUE TITLE
Internet-Of-Things devices interacting with each other

### ISSUE THREAD

**Issue by Wing-Li-oceanwing** [google/mobly#592]
I want to known how to interact with two IOT devices, not just android devices, eg:how to test the bluetooth module  of  a bluetooth headset and an Android device.Could you give me an example? Thank you!

**Comment by xpconanfan** [comment]
Which IOT device do you want to control?
You can create a mobly controller module module for that device yourself and use it.
For BT headset, see the discussion in #589
