### ISSUE TITLE
HFP testing without carkit device

### ISSUE THREAD

**Issue by aglogger** [google/mobly#623]
Is there a possibility to test e.g HFP Client functionality without having access to an android carkit device? Because as far as I can tell a lot of the Bluetooth test cases of the Android Comms Test Suite require a carkit device. Is there any kind of testdevice available so I don't need an acutal car for such testing. I tried out the new Android automotive emulator within Android Studio, but like the other Android emulators for Phones, etc. this one has no working Bluetooth emulation.

**Comment by xpconanfan** [comment]
Emulators won't be able to help here since they don't implement the BT stack.
You can potentially use a BT dongle and make it work like a HFP client.
Or you can just buy a car kit, which is commonly available since people buy them to put in their cars.
