### ISSUE TITLE
 The problem  of multiple devices running in the same case

### ISSUE THREAD

**Issue by sdwfclcyk1** [google/mobly#656]
This framework can only be used for a single device？
It  will prompt " Failed to start app and connect" when I run the script with two mobile phones at the same time and the same testcase.
How to solve the situation of multiple devices running in the same case?

**Comment by xpconanfan** [comment]
Can you provide the command you used and the logs?

**Comment by sdwfclcyk1** [comment]
**This is my configuration file**：
TestBeds:
  # A test bed where adb will find Android devices.
  - Name: SampleTestBed1
    Controllers:
      AndroidDevice:
        - serial: 66J5T18A19032058
          label: target

  - Name: SampleTestBed2
    Controllers:
       AndroidDevice:
         - serial: 46HDU19829005081
           label: discoverer
**and my run file :**
#!/bin/bash
for i in `seq 1 2`
do
{
    echo "$i"
    python hello_world_test.py -c sample_config.yml SampleTestBed$i
} &
done
wait  ##等待所有子后台进程结束

**Run logs with two devices  on the same time ** 
![image](https://user-images.githubusercontent.com/13634537/67664244-37575800-f9a2-11e9-835f-701a308626bf.png)

**Comment by sdwfclcyk1** [comment]
I want to run case with multiple devices and run at the same time.
For example, I want  a'l'l my device to click a button at the same time based on mobly.

**Comment by xpconanfan** [comment]
That's not a feature of mobly.

You need to either use subprocess to run commands in parallel, or run
multiple mobly tests in parallel.

**Comment by sdwfclcyk1** [comment]
![image](https://user-images.githubusercontent.com/13634537/67736333-3544d600-fa42-11e9-9dac-05923e03795f.png)
I am running multiple devices, prompting me that this file has failed. What is this file used for, can I delete it to solve this problem?

**Comment by xpconanfan** [comment]
Looks like your windows has some permission problems.
Did you run commands with elevated privilege before?
I'd try to remove everything under `tmp\\logs\\mobly` and try again.

**Comment by xpconanfan** [comment]
Closing since there has been no response for three days.
