### ISSUE TITLE
Snippet service's `is_alive` returns True even if the service is paused

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#665]
It is not clearly defined if a paused service should be considered alive.
We should probably make a decision and documents it.

**Comment by sarthak3248** [comment]
@xpconanfan  check out the given website:
https://mobly.readthedocs.io/en/stable/mobly.controllers.android_device_lib.services.html
Give updates!!

**Comment by xpconanfan** [comment]
Hi, can you provide more context on how your use case is affected by this issue? It'll help us address this problem better.
