### ISSUE TITLE
Implement an option to skip the remaining test suites, if a test fails during execution of suite runner.

### ISSUE THREAD

**Issue by santhosh12992** [google/mobly#673]
Hi,

If I am running multiple test suites using mobly suite runner, if a test suite fails, we need an option to abort or skip the remaining test suites.

Essentially, it means, we are following a sequence in the test execution and each test is a pre -requisite of following test suite.

Thanks.
-Santhoshkumar M

**Comment by xpconanfan** [comment]
You can already do this with `asserts.abort_all`

**Comment by santhosh12992** [comment]
Just a guess,

should we define 'on_fail(record)' [which is under mobly.base_test module] with asserts.abort_all in the suite_runner calling class?

**Comment by xpconanfan** [comment]
Not sure what you mean. Please clarify

**Comment by santhosh12992** [comment]
The goal is abort all the tests using the api that you have mentioned, ** only when there is a failed test case** across all test suite that is being run by suite runner.

Now the question is where to implement this, "asserts.abort_all".

**Comment by xpconanfan** [comment]
just call it in `on_fail`?

**Comment by santhosh12992** [comment]
Thanks.
