### ISSUE TITLE
INFO: How to toggle network connections like WIFI

### ISSUE THREAD

**Issue by sravanmedarapu** [google/mobly#68]
Is it possible to enable WIFI with out using adb command(`adb shell settings get global wifi_on`)? 

I mean possibility for accessing internal API like `wifiManager.setWifiEnabled(true)` in Java, Considering fact that adb is not reliable on higher versions like API 24 real devices. 

Would be more helpful if we have sample example how to handle network connections :)

**Comment by xpconanfan** [comment]
1. If you're able to use SL4A, it's pretty easy to toggle wifi. It's a simple call `ad.sl4a.wifiToggleState()`
2. You can also write a snippet using [Mobly Snippet Lib](https://github.com/google/mobly-snippet-lib). In your Java snippet code, you can obtain WifiManager and call its public APIs.

We are also working on pushing out a snippet apk with basic Android operations like toggling Wi-Fi :)

**Comment by sravanmedarapu** [comment]
Super quick response 👍 , will give a try and share my finding TQ :-)

**Comment by xpconanfan** [comment]
@sravanmedarapu any luck?
I was able to create a snippet that toggles Wi-Fi.
I built against the snippet lib source.
Let me know if you need any help.

**Comment by sravanmedarapu** [comment]
@xpconanfan, I stuck at building my app with SL4A dependency. I appreciate if you could share snippet :)

**Comment by dthkao** [comment]
Stravan, what sort of device are you testing on?

Sl4a is a standalone app in AOSP. It needs to be built for a particular
OS/device.

Snippets are different from sl4a. They are a device-side library that
should work on any android device.

**Comment by sravanmedarapu** [comment]
I am actually building a Utility server app to perform Actions on device, which needs to be run against different android OS versions (21 and above). For toggle wifi I am using Android `WifiManager's  setWifiEnabled()` but it is not working  in some real devices `API 24 and few API 23(One Plus One) ` because of the security level restrictions. 
Error message: 

`java.lang.SecurityException: xxx.server.test from uid 10240 not allowed to perform WIFI_CHANGE\n\tat android.app.AppOpsManager.noteOp(AppOpsManager.java:1888)\n\tat android.app.AppOpsManager.noteOp(AppOpsManager.java:1954)\n\tat android.net.wifi.WifiManager.setWifiEnabled(WifiManager.java:1471`

So thought of giving a try with `mobly` as I heard that it can also invoke hidden APIs as well :).

**Comment by xpconanfan** [comment]
So that looks like your app does not have the correct permission.
Do you have `android.permission.ACCESS_WIFI_STATE` and `android.permission.CHANGE_WIFI_STATE` in your manifest?

There is no hidden API needed to toggle Wi-Fi, and API 23/24 should work just fine.

I have sent you the source code I used in email. See if that helps :)

**Comment by sravanmedarapu** [comment]
Yeah, I did mentioned those in manifest file and could see them in granted permissions list as well.

Thanks for sharing source code, I will check my luck :).

**Comment by xpconanfan** [comment]
Any luck? :)
If there's no further question, shall we close this thread?

**Comment by sravanmedarapu** [comment]
Sure :)
