### ISSUE TITLE
Refresh adb connection to a device at the end of AndroidDevice teardown.

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#71]
Execute `adb -s <serial> reconnect` at the end of AndroidDevice controller object cleanup.

It has several benefits:
1. Kills any lingering adb processes/cmds that the test may have started and does not clean up properly.
2. Releases all forwarded adb ports.
3. Recovers unresponsive devices in some cases. Some devices may stop responding to all adb commands due to adb calls made by tests, leaving the device in an unusable state. Refreshing adb connection fixes the problem.

Overall this seems to be a good approach since it can clears any baggage a test may have left with adb and makes the execution cleaner.
The command does not affect other devices connected to the same host.

**Comment by adorokhine** [comment]
Is there any potential impact to other tests running concurrently? 'reconnect' doesn't mess with other connections/devices?

**Comment by xpconanfan** [comment]
Correct.
"The command does not affect other devices connected to the same host."
