### ISSUE TITLE
Support method "take_snapshot" in AndroidDevice

### ISSUE THREAD

**Issue by johnklee** [google/mobly#796]
From our user cases, we have to take screenshot of Phone quite a lot. Below is the code snippet for doing so:
```python
      # take screenshot
      screenshot_path = 'sdcard/screenshot_{}.png'.format(current_time)
      device.adb.shell('screencap -p {}'.format(screenshot_path))
      device.adb.pull([screenshot_path, log_path])
      device.adb.shell('rm -rf {}'.format(screenshot_path))
```
I think it might be a good idea to let controller [**AndroidDevice**](https://github.com/google/mobly/blob/master/mobly/controllers/android_device.py) to support it natively. Therefore, create this issue as feature request. Thanks!

**Comment by xpconanfan** [comment]
We already have `take_screenshot` in `AndroidDevice` right?
https://github.com/google/mobly/blob/master/mobly/controllers/android_device.py#L1034

**Comment by johnklee** [comment]
Cool! Thanks for the reminder and it is of great help to us to learn that this useful method is already supported! I should check the source code first. Then this issue is no longer needed.

**Comment by xpconanfan** [comment]
"prefix" is the field that you can customize.
The API handles addition of device identity and name de-dupe in filenames.
It's probably better than trying to create yet another system to do the same thing with file names.

We recommend you use `AndroidDevice#generate_filename` for all your file names related to Android devices.

**Comment by johnklee** [comment]
Understood. Thanks for the explanation and feedback.
