### ISSUE TITLE
Make test_run_summary reporting consistent.

### ISSUE THREAD

**Issue by dthkao** [google/mobly#81]
In the Results array of the summary, the number of entries and whether there is an Extra error message currently differs depending on where the test failed.

1) We should have a result for every test case requested (explicitly or implicitly)
2) We should use extr error to surface the point of failure (e.g., setup_class, setup_test, abort, teardown_test, etc.)

**Comment by xpconanfan** [comment]
We can't know for sure how many tests were requested due to generated tests.
Extra error should already record the point of failure, can you provide a way to reprod the issue you're seeing?

**Comment by xpconanfan** [comment]
Duplicate of #41
