### ISSUE TITLE
Remove Python 3.6 hook from CI

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#828]
We have removed Py36 env from our CI, but the Py36 hooks are still showing up as "waiting" in every PR.
This forces us to have to force submit every PR.

Let's remove Py36 for good.

**Comment by booneng** [comment]
"You can remove the outdated check in the protected branch settings of the repository settings." - https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157/4

Looks like we need someone with admin access to do this.

**Comment by xpconanfan** [comment]
Done. Thanks!
