### ISSUE TITLE
Question on using mobly to interact with multiple android displays ?

### ISSUE THREAD

**Issue by alokps** [google/mobly#831]
Is there a way we can use mobly with multiple android displays, if yes are there are any examples that can be pointed.

**Comment by xpconanfan** [comment]
Can you clarify what you mean by multiple Android displays?
Are these multiple Android devices serving as displays in a scenario?

**Comment by xpconanfan** [comment]
If it's APIs you just call them via Mobly snippets?

Sorry this question is too vague

**Comment by alokps** [comment]
> If it's APIs you just call them via Mobly snippets?
> 
> Sorry this question is too vague

apologies for late reply on this, I dont believe its just an API call, so if the use case requires to interact with a primary display and then switch over to secondary display to interact with it how do we do that. There are no clear details on how to switch between these 2 displays, any pointers or links would be helpful

**Comment by alokps** [comment]
sounds good.
