### ISSUE TITLE
Snippet client's _is_app_running() doesn't work properly, leading to race conditions

### ISSUE THREAD

**Issue by adorokhine** [google/mobly#88]
Slow loading snippets fail because _is_app_running() returns True even when nothing is on the other side of the socket.
This leads to race conditions between the snippet app really starting and the connection attempt.

```
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> print self._port
8822
>>> result = sock.connect_ex(('127.0.0.1', self._port))
>>> print result
0
And yet...
$ nc 127.0.0.1 8822
$
```

**Comment by xpconanfan** [comment]
We actually used to hit this all the time with sl4a client...
