### ISSUE TITLE
Check that some views are present on Activity

### ISSUE THREAD

**Issue by AntonMalyshev** [google/mobly#888]
Hi guys,
How can I test that my activity has specific TextViews displaying specific text, do you have some functions for that?

**Comment by xpconanfan** [comment]
This is not a mobly question? Pls check Android resources.

**Comment by AntonMalyshev** [comment]
Doesn't Mobly provide this functionality?

**Comment by xpconanfan** [comment]
Just like Mobly doesn't provide the functionality of installing apks.
But it doesn't mean you can't install apks in Mobly tests.

**Comment by AntonMalyshev** [comment]
I see, thank you. Probably I misunderstood what can be done with Mobly. The [documentation](https://source.android.com/docs/automotive/tools/ui-frameworks) suggests to use it only for the testing of end-to-end Bluetooth connectivity...

**Comment by xpconanfan** [comment]
Ah I see.
Sorry about the confusion. We don't own that particular page.
Thanks for bringing it to our attention.

Mobly is used for BT testing for sure, but it's not the only use case of it :)

**Comment by AntonMalyshev** [comment]
Anyway, regarding the original question is Mobly good for end to end UI testing of some Android app screens or is it better to use Espresso or Appium? Would really appreciate any guidance here / references to documentation / etc.

**Comment by xpconanfan** [comment]
The decision is really up to you.

You can use https://github.com/google/snippet-uiautomator in Mobly tests to operate app UIs.
It's pretty easy to set up. You can give it a try.
