### ISSUE TITLE
No name 'snippet' in module 'mobly.snippet'

### ISSUE THREAD

**Issue by vinayadasepalli** [google/mobly#925]
@xpconanfan 

from mobly.snippet import snippet

Error message : No name 'snippet' in module 'mobly.snippet'

**Comment by xpconanfan** [comment]
No idea what this means.
Closing as it's not actionable

**Comment by vinayadasepalli** [comment]
I copied the code into the VS Code editor and attempted to run it. However, I encountered an error:

Error message: No name 'snippet' in module 'mobly.snippet'
I have attached a screenshot of the error for your reference.

Could you please advise on how to resolve this import error?
<img width="1026" alt="Screenshot 2024-07-19 at 9 50 25 AM" src="https://github.com/user-attachments/assets/4fa09db6-41f2-4d94-8d00-4e3b2d5089c1">

**Comment by mhaoli** [comment]
This is clearly your environment's problem.

Maybe your VS is borken, you did not install mobly successfully, or you installed a version that is too old.

Please debug your own environment.

**Comment by vinayadasepalli** [comment]
@mhaoli 

'''
Requirement already satisfied: mobly in /Library/Python/3.9/site-packages (1.12.2)
Requirement already satisfied: portpicker in /Library/Python/3.9/site-packages (from mobly) (1.6.0)
Requirement already satisfied: pyyaml in /Library/Python/3.9/site-packages (from mobly) (6.0.1)
```

**Comment by xpconanfan** [comment]
This is some basic stuff you should sort out yourself.
It's not our job to teach you how to do your job.
