### ISSUE TITLE
Test results format compatible with CI/CD servers

### ISSUE THREAD

**Issue by cosminstirbu** [google/mobly#930]
Hello,

My understanding is that the current test results .yaml format is a custom one, not compatible with CI/CD servers such as Github Actions, Jenkins, Azure DevOps.

Is there any out of the box mechanism to control the results format? For instance have the format in JUnit?

Thank you,
Cosmin

**Comment by xpconanfan** [comment]
Mobly results are designed for complex tests, so they don't fit into things like JUnit.

The usual practice is for people to write their own converter between Mobly format and whichever format they want.
