### ISSUE TITLE
How do you tag and run just a subset of tests?

### ISSUE THREAD

**Issue by cosminstirbu** [google/mobly#931]
Hello,

What is the recommended way to tag and run just a subset of tests?

I understand that now you can selectively specify what test cases to be run by passing them by name like `$ python hello_world_test.py -c sample_config.yml --test_case test_bye test_hello test_bye`, however I'd like to tag tests with `smoke`, `sanity`, `regression` and pass the tag name instead of each individual test case name.

Do I need to write some sort of utility that scans and identifies the tests, and then pass them by their name to Mobly?

Thank you,
Cosmin

**Comment by xpconanfan** [comment]
you can build your own suite with different sets of test cases, inheriting from the `base_suite`.
