### ISSUE TITLE
Flake in unit tests

### ISSUE THREAD

**Issue by adorokhine** [google/mobly#97]
Reported in #87 
https://travis-ci.org/google/mobly/jobs/197104959

=================================== FAILURES ===================================
____________________ UtilsTest.test_start_standing_subproc _____________________
self = <tests.mobly.utils_test.UtilsTest testMethod=test_start_standing_subproc>
    def test_start_standing_subproc(self):
        with self.assertRaisesRegexp(utils.Error,
                                     "Process .* has terminated"):
\>           utils.start_standing_subprocess("sleep 0", check_health_delay=0.1)
E           AssertionError: Error not raised
tests/mobly/utils_test.py:32: AssertionErro

**Comment by xpconanfan** [comment]
This is odd.
It means in this run, the process of `sleep 0` was still alive when we check it 0.1s after it started...

**Comment by adorokhine** [comment]
Friendly ping, this keeps coming up
